version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: myapp
      MYSQL_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  db_staging:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_staging
      MYSQL_USER: myapp_staging
      MYSQL_PASSWORD: staging_password
    volumes:
      - mysql_staging_volume:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bin/dev & bin/rails s -p 3000 -b '0.0.0.0' && wait"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: myapp
      MYSQL_PASSWORD: password
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
      - db_staging

volumes:
  mysql_volume:
  mysql_staging_volume:
