default: &default
  adapter: mysql2
  encoding: utf8
  username: myapp
  password: password
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  collation: utf8_general_ci

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
